import numpy as np
from pathlib import Path
thisfolder = Path(__file__).parent.absolute()
pkg_root = thisfolder.parent.absolute()

shared_kernel_descriptions = {
    'p2m_rectmesh3d':{
        'args':(
            (('scalar', np.int32),   'nparticles',),
            (('array',  np.float64), 'x',),
            (('array',  np.float64), 'y',),
            (('array',  np.float64), 'z',),
            (('array',  np.float64), 'part_weights'),
            (('scalar', np.float64), 'x0',),
            (('scalar', np.float64), 'y0',),
            (('scalar', np.float64), 'z0',),
            (('scalar', np.float64), 'dx',),
            (('scalar', np.float64), 'dy',),
            (('scalar', np.float64), 'dz',),
            (('scalar', np.int32),   'nx',),
            (('scalar', np.int32),   'ny',),
            (('scalar', np.int32),   'nz',),
            (('array',  np.float64), 'grid1d'),),
        'num_threads_from_arg': 'nparticles'
        }
    }



pocl_default_kernels = {
    'kernel_descriptions': shared_kernel_descriptions,
    'src_files': [
        pkg_root.joinpath('src_c/atomicadd.clh'),
        pkg_root.joinpath('src_autogenerated/linear_interpolators_pocl.clh')
        ]
    }

